/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void LED_Init(){
	uint32_t volatile *pClkctrlreg = (uint32_t*)0x40021014;
	uint32_t volatile *pPortModereg=(uint32_t *)0x48000000; //PORT_A + offset of mode
	uint32_t volatile *pPortOutreg=(uint32_t *)0x48000014; ////PORT_A + offset of data out

	*pClkctrlreg |=(1<<17);
	*pClkctrlreg |=(1<<19);
	*pPortModereg &= ~(0b11<<10);
	*pPortModereg |= (0b01 <<10);
	*pPortOutreg |= (1 << 5);


}
void Button_Init(){
	//USER B1 is connected to PC13(0x4800 0800)
	uint32_t volatile * const pPortModeregC = (uint32_t *)0x48000800;
	*pPortModeregC &= ~(0b11<<26);
}

void LED_ON(){
	uint32_t volatile *pPortOutreg=(uint32_t *)0x48000014;
	*pPortOutreg |= (1 << 5);
}
void LED_OFF(){
	uint32_t volatile *pPortOutreg=(uint32_t *)0x48000014;
	*pPortOutreg &= ~(1 << 5);
}
int main(void)
{
	uint32_t  volatile *pPortInRegC= (uint32_t *)0x48000810;
		LED_Init();
		Button_Init();
	    /* Loop forever */
		while(1){
			int volatile pin_st = (*pPortInRegC )& (1<<13);

			if((pin_st )){
				LED_OFF();
			}else LED_ON();
		}
}
